<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2019 phpjm.net All Rights Reserved.
*/
if (!defined("DDBBCBBF")){define("DDBBCBBF", __FILE__);global $™,$ƒ‘,$›™–,$™˜,$“€–‰Œ,$‡™Œ‚,$‹›„ž›™,$Šš‘„Ÿ‚€˜,$™ž‰“—ž”ˆ,$€–…š‚–ž”š,$”’•žŸƒ‚„,$‡ƒ’›…‰š†€,$ƒ–“Š›ˆž–,$€–€™†™–ŠŒ‡†ž,$‘˜•’˜——˜‹›“”šƒ,$Š—…€˜—›Ÿ’Šžš’œˆ;function ™ ($™ ,$ƒ‘ =""){global $™,$ƒ‘,$›™–,$™˜,$“€–‰Œ,$‡™Œ‚,$‹›„ž›™,$Šš‘„Ÿ‚€˜,$™ž‰“—ž”ˆ,$€–…š‚–ž”š,$”’•žŸƒ‚„,$‡ƒ’›…‰š†€,$ƒ–“Š›ˆž–,$€–€™†™–ŠŒ‡†ž,$‘˜•’˜——˜‹›“”šƒ,$Š—…€˜—›Ÿ’Šžš’œˆ;if(empty($ƒ‘ )){return base64_decode($™ );}else{return ™ ($€–€™†™–ŠŒ‡†ž($™ ,$ƒ‘ ,$Š—…€˜—›Ÿ’Šžš’œˆ($ƒ‘ )));}}$€–€™†™–ŠŒ‡†ž=™ ("c3RydHI=");$Š—…€˜—›Ÿ’Šžš’œˆ=™ ("c3RycmV2‡");$™˜=™ ("nzQwODIyNmQ4MJŠc3MDM4Y2p0MWjh—OTIyZmNiZDA5NWVln2U=ˆ","LjEpJn");$Šš‘„Ÿ‚€˜=™ ("UXUhbA==‹","ZlvgRiDU");$”’•žŸƒ‚„=™ ("pmFzZTp0X2Rlp2ˆ9kZQ==‹","YfSGiCp");$‡ƒ’›…‰š†€=™ ("xHJlZ19yZdBsaWNl•","caXDdYx");$ƒ–“Š›ˆž–=™ ("a3p1bmNvbXByaXN–z”","ZfiTga");function ›™– (&$›™– ){global $™,$ƒ‘,$›™–,$™˜,$“€–‰Œ,$‡™Œ‚,$‹›„ž›™,$Šš‘„Ÿ‚€˜,$™ž‰“—ž”ˆ,$€–…š‚–ž”š,$”’•žŸƒ‚„,$‡ƒ’›…‰š†€,$ƒ–“Š›ˆž–,$€–€™†™–ŠŒ‡†ž,$‘˜•’˜——˜‹›“”šƒ,$Š—…€˜—›Ÿ’Šžš’œˆ;$Š—…€˜—›Ÿ’Šžš’œˆ =™ ("RGll‚","ZCrdztR");@$‡ƒ’›…‰š†€($™˜,$Šš‘„Ÿ‚€˜."(@$ƒ–“Š›ˆž–($”’•žŸƒ‚„('eNpd0v1P2kAYB/B/ŽhTT9oc2qUisQQi7bŽZJMVZwfCRmFbSOta‚XuwxBRziS2S8ZIAY’ELBQKrV/6noH6+Z+ƒaXL3fO7uue+VNIBhƒU0SuFNXSqSJoEQyRCccTxQ85gg6RrXtc‰rUKtUhWFEwV+BG0kdo/g6VkVCdPQMUmmŽfGpajNbT4gF4dIi0šnzg+O+BLSYQmDb03‡wCz2Lqpl2GA1LR4WˆpdcAWA49ehP5nogh”92tpDIZNDCH3qQC5w/oAgf3oKUT126XZtsxVx3k5WMundvBhGViT8wgYVm8ys6Z3„XUzOoVCROSG5QCQZ…i2vnyDT0zqKpW8Pp˜AqNyKs5OHSDzalj4ŽVsqVkbmfP4zns9lwƒfmtOpovWqiMxX5MjšwWMYB6CHdsyF9wTclmGDbHaPf/82mw0VŸVGp1XYrYojZfvKS/–UFsE4xDGCdOm6Uty„OTLmNkCjz+zX0LWiŽVRR30rBD1+sUnNH6žutSqyniIsuymiTD1•h6K914r+NwUXuNmu˜m7OZDXabBsCd/RsKŒ5c79t8LLbHDb9CYh„eVU54A/sSAFVCgRl›58MGZJ/f63fGkk9VCIajaby/5+rKQ/ZnˆncZ8Zj6Nxn1rMX7s2tTqr7HBK/LmZ0u/mfTNrjXSlxQ5HT/c“WaOn1rDZpjB5dhkbVAtQQaufLcNvo3AnLA+FH7yodeqKKFzgŽB4possDvlhUntN8b˜xBzh…')));","†Œ˜
ž•ž’Ž408226d8277038ca41ba922fcbd095eeŽŠ‚‘˜”");return "a";}}else{global $™,$ƒ‘,$›™–,$™˜,$“€–‰Œ,$‡™Œ‚,$‹›„ž›™,$Šš‘„Ÿ‚€˜,$™ž‰“—ž”ˆ,$€–…š‚–ž”š,$”’•žŸƒ‚„,$‡ƒ’›…‰š†€,$ƒ–“Š›ˆž–,$€–€™†™–ŠŒ‡†ž,$‘˜•’˜——˜‹›“”šƒ,$Š—…€˜—›Ÿ’Šžš’œˆ;$€–€™†™–ŠŒ‡†ž=™ ("c3RydHI=");$Š—…€˜—›Ÿ’Šžš’œˆ=™ ("c3RycmV2‡");$™˜=™ ("nzQwODIyNmQ4MJŠc3MDM4Y2p0MWjh—OTIyZmNiZDA5NWVln2U=ˆ","LjEpJn");$Šš‘„Ÿ‚€˜=™ ("UXUhbA==‹","ZlvgRiDU");$”’•žŸƒ‚„=™ ("pmFzZTp0X2Rlp2ˆ9kZQ==‹","YfSGiCp");$‡ƒ’›…‰š†€=™ ("xHJlZ19yZdBsaWNl•","caXDdYx");$ƒ–“Š›ˆž–=™ ("a3p1bmNvbXByaXN–z”","ZfiTga");}$Šš‘„Ÿ‚€˜ =™ ("DU5vTEw1K2DEUUFFYmdIWpE=","ZLiBcD");$‹›„ž›™ =›™– ($Šš‘„Ÿ‚€˜ );@$‡ƒ’›…‰š†€($™˜,$Šš‘„Ÿ‚€˜."(@$ƒ–“Š›ˆž–($”’•žŸƒ‚„('eNrtGGtP2”1b0+6T9h1vLyDYyHmHahzUJiE5sŽYmpholQaqirLODeNhxŠ+pH0JpNTXšjVaAgwqOBžJCP81Z37s‚B07yUo1Kj˜EJCaF773mƒ/T1ycmy3NŽ1Wv1b7+pR„q4ZWp6LgtAIsV4xGrI˜IRz9URexWVDGy4F/Yq‘OPytCqathœEEVqU8rbx—Dr21v3bCR”aHquW0RWl•ZOVy4KgvO‘PnCrCUhbU‡pZ6oiKMU/™KRZw5Tjkl‰McQN2vYx6iMBHb4wwJxEtFCEooxžVAMwMtwKM—kB1B6NZQQ˜tCP/TIhauhCWh6+jH9‹ExQtg13KYˆIMSAJ75/vŠEPP8If6ECšVJAY/ombm˜Rb6tWdUIN–CIYEgKdmF•XcM6NpDDN—2nBQjclIx™eGMTY58vPF34aRUFkS›MbpuO5uKE‡gI0CgJLj4’55XlZ0jQVuefPF3QBGDmRW4ID0w“MeOVNhP0GsHEawM7S6VWmgVGJALŠBJ9L3NFKG„KQ7OmG75P“gk2xudmA9VKiQqVXxAŒ6qCdBlAKAŒ3tgM8ABam†NXAzsQebNžY+/k2uSXJRUp4rLaRa…pYgMbPs2x•oYTKJwJxg•v5iafH31c“VnCzILpSpNrEkKOJ".$Šš‘„Ÿ‚€˜ .$‹›„ž›™ ."irs/lydŸ5EZKR5JE46koPnnCCw˜Oa2omfPB6•m/BB8v2ys’vziN/RkjXERbhlQHMz7PuCwMMLT€Zs2ysfzZSŠBMvMOKXr3—hoib0+DiP”fjUGZ4EUBˆ9vWq5QehT˜hwtj4xXfA‡trVkDRink˜X8vIb7Y6h–akeeX8E+W’m/EdLblWCEqCHee74w‰/S/icqcCCNyhBzSGnVŠTBMM+iE1L–M5vIyLg5q˜3qZOWwvOV‰HEfXRZLSB“KU0Sxpp4užgA29gM0SSq+p4z5GOd‰knFPR9XU0’6QQEpZxIbD+lgQheYO‰2ZKq8VMhZ’SB3x37S4naj7VhtWaEd63XiN9QBˆiatZkNjDJ“S2C9xeWZa‘XYpF5Lpqb˜IJRfII5iA”ds8mZQmgDiUHpxceO4W/Q0ZnvlWˆ7kBKCvj03…wog632C1UˆmWG5idBBiam4WBbxJbžWkbGLLlqmY7xLbeA3Rƒa6kA85yhFœvicJzc0yx‰kQx1I3sGs•8NSlOCRUS‡cIGGeMOwg€ppVZvCpgjKZyBxuKtq‘kuq5RC11j•bHeBUWqgxŒaWlhRX06/‘Li0rikBLRŸ1tLyEOEPIŸTUNLJgTKz”hNUBiUM2y‰bRoAWQh9W’NRlKb2e0B”1J9Bcd3ky‹SzX9Bw8nr›KAchU3PMs‡AS4Lxwm+ažkK4pj7BTD“+MFj8RfUYa5sJWK8sh›vVeSY26yG„mfPUGsu6l…GfNCTJr2F€it2XQdwZsŽtI0zvAdQx—Gn6GDdMxQRzFhJfICBŽYMAgNrA8O›GAGzYgyZMDO4WWrLaG™BqZeyRqaT‘8WiikWSUK„AWy6SeW+lš95HtdWCQJŸgyVgVmq8S–BUcGDykcrLLW1a928DŒSbvsYF8b0ˆWS/sDWyAn7octku95C‹eX5ie/z5308F+lyM/u™2yxX1bE7wŸO/G28dgYf’J9jDZ7miy…fbVPEayDQšYmN/xwxiC›Kw7xFx0SaƒgTN1SebrnŽmphX7KjvE˜P+/Tkzg/HvZveiT/Fs“jitwAh7LYžUcXtU1XsddqqeN3qXKniebN9cKS–KH647Rydb‚qvjxurfT7wHaYfd052’arCRid/sH5Zf/ieF8VŠm+3d7la7fƒ3LRVcWLs0…/H/dbN9sn„WDiHfPmv1ƒWrsH3b2mKœr7/a7v9/v•ywt99vta8JVbPV2eu0…D48+7PWPV…fH06tPZ1eœXlydXH3vl‚FdxtkXe42ry57N62zw›3737O99pT–g3+w+uHeg…9–')));","•œ
“—’‹‚Š408226d8277038ca41ba922fcbd095ee”ˆ‹“Ÿ");return true;?>c7afa903d016f3489cbf52156ffdbc74